apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       my-deployment
  updatePolicy:
    updateMode: "Auto"


Options for updateMode:

Auto: VPA automatically adjusts the resource requests for the pods based on the observed usage.

Initial: VPA sets the initial resource requests for the pods when they are created, but does not update them afterward.

Off: VPA does not automatically update the resource requests for the pods.
