apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: myFirstApp
spec:
  replicas: 1
  backofflimit: 4
  selector:
    matchLabels:
      template: testTemplate
  template:
    metadata:
      name: podTemplate
      labels:
        template: testTemplate
    spec:
      containers:
        name: myFirstContainer
        image: <ACR name>.azurecr.io/<repo name>:<version>
        ports: 
          containerPort: 3000
        resources:
          limits:
             cpu: 500m
             memeory: 200Mi
          requests:
             cpu: 200m
             memeory: 100Mi
        env:
          name: password
          value: 123456789
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1