apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  activeDeadlineSeconds: 100 #dlt pods after his secs
  completions: 10
  parallelism: 3
  completionMode: Indexed  # required for the feature
  backoffLimitPerIndex: 1  # maximal number of failures per index
  maxFailedIndexes: 5      # maximal number of failed indexes before terminating the Job execution
  template:
    spec:
      
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4


apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
  namespace: default
  labels:
    app: job-label
spec:
  template:
    metadata:
      labels:
        app: job-label
    spec:
      containers:
      - name: container-name
        image: container-image
        ports:
        - containerPort: 80
        command: []
        env:
        - name: ENV_VAR_NAME
          valueFrom:
            configMapKeyRef:
              name: config-map-name
              key: config-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: volume-name
          mountPath: /mnt/path
      volumes:
      - name: volume-name
        persistentVolumeClaim:
          claimName: pvc-name
      restartPolicy: Never
  backoffLimit: 4


