apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: default
spec:
  limits:
  - max:
      cpu: "2"
      memory: "1Gi"
    min:
      cpu: "200m"
      memory: "100Mi"
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "300m"
      memory: "200Mi"
    type: Container
